
version: 2

models:
  - name: case_statement
    description: "A dbt sql example applying hard-coded case statement"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      
      - name: name
        description: "Name of people"
        data_tests:
          - not_null
      
      - name: gender
        description: "Gender of people"
        data_tests:
          - not_null
          - accepted_values:
              values: ['M', 'F']
      
      - name: age_of_death
        description: "Age of death"